<a href="https://colab.research.google.com/github/itimes-digital/estudo-python-git/blob/master/estudo_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
def outro_teste():
    for i in np.random.randn(5, 5):
        print(i)

In [3]:
outro_teste()

[-0.59866192  0.70372142  0.28174981  1.14090966  0.38197482]
[-0.99384972  0.24413807 -0.26277195 -1.51655388  1.51116983]
[0.08069327 0.23839268 1.56663369 0.00607059 1.66342777]
[-1.41572557  0.23734375  0.80295268  0.34754855  1.38931704]
[ 1.16719215  0.16508121 -0.23086552 -0.5838888  -1.08363906]


In [4]:
a = 5; b = 6; c = 7

In [5]:
print(a, b, c)

5 6 7


In [6]:
a = [1, 2, 3]

In [7]:
b = a

In [8]:
a.append(b)

In [9]:
b

[1, 2, 3, [...]]

In [10]:
a

[1, 2, 3, [...]]

In [11]:
a = 5

In [12]:
isinstance(a, int)

True

In [13]:
isinstance(a, str)

False

In [14]:
isinstance(a, (int, str))

True

In [15]:
a = 'foo'

In [16]:
getattr(a, 'split')

<function str.split>

In [17]:
hasattr(a, 'split')

True

In [18]:
c = 1

In [19]:
def isiterable(obj):
    try:
        iter(obj)
        return True;
    except TypeError: # não é iterável
        return False;

In [20]:
isiterable(a)

True

In [21]:
isiterable(c)

False

In [22]:
isiterable('isso será iterável')

True

In [23]:
isiterable([1,2,3,4])

True

In [24]:
isiterable(10)

False

In [25]:
a = None

In [26]:
a is None

True

In [27]:
a = 10
b = 3

In [28]:
a / 3

3.3333333333333335

In [29]:
a // 3

3

In [30]:
a ** b

1000

In [31]:
a & b

2

In [32]:
a and b

3

In [33]:
a = 1

In [34]:
b = 2

In [35]:
a & b

0

In [36]:
b = 1
a & b

1

In [37]:
x = 'a'
z = 'b'

In [38]:
if x and z:
    print(True)
else:
    print(False)

True


In [39]:
a_list = ['foo', 2, [4, 5]] # lista mutável

In [40]:
a_list[2] = (3,4)

In [41]:
a_list

['foo', 2, (3, 4)]

In [42]:
a_tuple = (3,5, (4,5)) # lista não mutável, recomendável
a_tuple[1] = 'four'

TypeError: ignored

In [43]:
ival = 17239871

In [44]:
ival ** 6

26254519291092456596965462913230729701102721

In [45]:
fval = 7.243

In [46]:
fval2 = 6.78e-5

In [47]:
a = 3
b = 2
type(a), type(b)

(int, int)

In [48]:
c = 3 / 2
c

1.5

In [49]:
type(c)

float

In [50]:
3 // 2 # sem fração

1

In [51]:
s = 'cinema'
list(s)

['c', 'i', 'n', 'e', 'm', 'a']

In [56]:
s[:3], s[5:6] # três primeiras letras e depois a última letra

('cin', 'a')

In [58]:
a = r'this\has\no\special\characters'
a

'this\\has\\no\\special\\characters'

In [60]:
template = '{0:.2f} {1:s} are worth US${2:d}'
template.format(4.5560, 'Argentine Pesos', 1)

'4.56 Argentine Pesos are worth US$1'

In [63]:
val = 'español'
val

'español'

In [64]:
val_utf8 = val.encode('utf-8')
val_utf8

b'espa\xc3\xb1ol'

In [65]:
type(val_utf8)

bytes

In [66]:
bytes_val = b'this is bytes'
bytes_val

b'this is bytes'

In [68]:
decoded = bytes_val.decode('utf8')
decoded # é str (Unicode) agora

'this is bytes'

In [69]:
from datetime import datetime, date, time

In [71]:
dt = datetime(2011, 10, 29, 20, 30, 21)

In [72]:
dt.day

29

In [73]:
dt.hour, dt.minute, dt.second

(20, 30, 21)

In [74]:
dt.date()

datetime.date(2011, 10, 29)

In [75]:
dt.time()

datetime.time(20, 30, 21)

In [81]:
dt.strftime('%m/%d/%Y %H:%M')

'10/29/2011 20:30'

In [83]:
sequence = [1, 2, None, 4, None, 5]
total = 0
for value in sequence:
    if value is None:
        continue
    total += value

total

12

In [86]:
x = 0
if x < 0:
    print('negative!')
elif x == 0:
    # TODO: insira algo inteligente aqui
    print('olá...')
    pass
else:
    print('positive!')

olá...


In [87]:
range(10)

range(0, 10)

In [88]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [89]:
sum = 0
for i in range(100000):
    # % é o operador de módulo
    if i % 3 == 0 or i % 5 == 0:
        sum += i 

sum

2333316668

In [90]:
x = 5
'Non-negative' if x >= 0 else 'Negative'

'Non-negative'